# Generated by Django 4.0.4 on 2022-06-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('relationship', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('cellphone', models.IntegerField()),
            ],
        ),
    ]
